name: Deploy

on:
  pull_request:
    branches: master
  push:
    tags: v[0-9]+.[0-9]+.[0-9]+
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Poetry setup
        uses: Gr1N/setup-poetry@v4

      - name: Install dependencies
        run: poetry install

      - name: Lint
        run: poetry run flake8

      - name: Type checking
        run: poetry run mypy

      - name: Test
        run: poetry run pytest -vv --skip-execs

      - name: Heroku deploy
        if: startsWith( github.ref, 'refs/tags/' )
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "${{ secrets.HEROKU_APP_NAME }}"
          heroku_email: "${{ secrets.HEROKU_EMAIL }}"
          usedocker: true
